### ISSUE TITLE
Parsing hexadecimal values

### ISSUE THREAD

**Issue by phodina** [miam-miam100/prse#15]
Hi,
could you please suggest how to parse the hexadecimal values?

Is there a possibility to specify the radix different than 10?

**Comment by miam-miam100** [comment]
Hiya there is no direct support for parsing hexadecimal values but you can easily write your own custom parser. Something like this should work:
```rs
use prse::{prse, Parse};

struct Hex(i32);

impl<'a> Parse<'a> for Hex {
    fn from_str(s: &'a str) -> Result<Self, ParseError> {
        i32::from_str_radix(s, 16) //Using 16 for hexadecimal
    }
}

let v: Hex = prse!("A", "{}");
```

**Comment by miam-miam100** [comment]
Added some extra documentation to better cover this case in #17
