### ISSUE TITLE
Support for parsing with a variable number of separator

### ISSUE THREAD

**Issue by mikeyoung3k** [miam-miam100/prse#21]
Is it possible to support parsing an arbitrary number of separators as if they were one? e.g.

```
let line = "ID: 5, favourite numbers: 1---6-2-6---3-3333---------4"
let res: (usize, vec<usize>) = prse::parse!(line,"ID: {}, favourite numbers: {:-:}");
println!("{:?}",res.1") // 1,6,2,6,3,3333,4
```

**Comment by pavloslav** [comment]
Same issue. Possible solution (not perfect, but works pretty well):
```
let (res0, it): (usize, _) = prse::parse!(line,"ID: {}, favourite numbers: {:-:0}");
let res1: Vec<usize> = it.filter(|s|s!=Ok("")) //filter out empty strings between separators
                                      .map(|x|x.unwrap().parse::<usize>().unwrap())
                                      .collect();
```
In fact, I'm using `try_parse!`, and `?` operator makes it even shorter.

For single variables (not iterators) with unknown number of separators, scan into `&str` and use trim.

**Comment by pavloslav** [comment]
I've opened a pull request for this

**Comment by pavloslav** [comment]
Shouldn't you bump the version number? It's a major change, maybe 1.1.0?

**Comment by miam-miam100** [comment]
Yep, just have few more changes I want to make before pushing a release out
